### ISSUE TITLE
Genel

### ISSUE THREAD

**Issue by VB10** [Flattih/flutter-obilet-clone#1]
https://github.com/Flattih/flutter-obilet-clone/blob/09eaa02eb154b02ef97a81a9991937a501ac9750/lib/features/home/notifiers/expedition_controller.dart#L64

- bu methoddan başlayarak hiçbir zaman bu kadar uzun bir method yapıp iç içe girdirmene gerek yok misal bir state pattern yapaiblrisin ilgili durumları kendi içinde uyana göre hande eder bir çok design kalıbı uygun olur
- river pod özelinde forcelemer vs gördüm bunlara dikkat etmek lazım
- modeller equatable olsun json seriazlbe olsun eksik duruyor
- very good anlayis ekleyeiblirsin
- sınıf isimleri ile dosya isimi tutarsızlkarı var
- classın içinde olmayan method veriable kullanımlarını aza indirmek laızm riverpod dışında
- localizasyon yok iç içe giren widgetler göze çarpıyor
- daha iyi bir readme

eline emeğine sağlık

**Comment by Flattih** [comment]
Teşekkürler abi amacım aslında biraz hızlıca uygulamayı bitirmekti :)
